delete unchanged previous files
WatWowMap/Masterfile-Generator pull request #39
Opened 2022-12-20 15:30 UTC by Fabio1988

As there is now a daily sync it's annoying to create a daily commit if nothing changed. therefore I added a comparison of content, if it's unchanged we delete old file again. if the newly created directory `previous-versions/$sha` is empty it should not be commited and therefor the workflow does not create a commit :+1:

2022-12-20 15:31 UTC, Fabio1988 commented on generate.js
> +      if (previousFile.equals(newFile)) {
https://nodejs.org/api/all.html#buffer_buf_equals_otherbuffer

2022-12-22 17:27 UTC, TurtIeSocks requested changes
Small, minor changes, everything works great though! Thanks so much, this will be awesome to have!

2022-12-22 17:27 UTC, TurtIeSocks commented on generate.js
> +      var newFile = fs.readFileSync(`./${templateName}`)
```suggestion
      const newFile = fs.readFileSync(`./${templateName}`)
```
Please change these to `const`

2022-12-22 17:27 UTC, TurtIeSocks commented on generate.js
> +      var previousFile = fs.readFileSync(previousFilePath)
```suggestion
      const previousFile = fs.readFileSync(previousFilePath)
```

2022-12-22 18:30 UTC, TurtIeSocks approved these changes

2022-12-22 18:30 UTC, merged